yaml
name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:   

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate WakaTime stats
        uses: wakatime/wakatime-readme-action@v1
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          filename: README.md
 ⁠
